### PR TITLE
:fire: DOP-4290 removes Manifest.py and Document.py as part of the deprecating of the legacy tooling support

### PR DESCRIPTION
**Pull request by caesarbell**

### CODE REVIEW

**Review by anabellabuckvar — COMMENTED** [review]
Thanks for this! README looks great. Two notes
1. I think there are a few dependencies that were only used in Document.py and/or Manifest.py, such as `html5_parser` and `lxml`(but possibly more). What do you think about checking and removing such dependencies from setup.py and pyroject.toml?
2. I could be wrong, but it seems like there is still some code for legacy tooling that uses giza/sphinx and deals with building manifests from an html document. I noticed this in `convert_redirects`, for example, but please ignore if you already saw that code and decided to leave it in!

**Comment by caesarbell** [comment]
> Thanks for this! README looks great. Two notes
> 
> 1. I think there are a few dependencies that were only used in Document.py and/or Manifest.py, such as `html5_parser` and `lxml`(but possibly more). What do you think about checking and removing such dependencies from setup.py and pyroject.toml?
> 2. I could be wrong, but it seems like there is still some code for legacy tooling that uses giza/sphinx and deals with building manifests from an html document. I noticed this in `convert_redirects`, for example, but please ignore if you already saw that code and decided to leave it in!

@anabellabuckvar good catch, I also removed it from those dependencies from `requirement.txt` as well. As for the `convert_redirects.py`, how can I confirm that this was used for legacy tooling?

**Comment by anabellabuckvar** [comment]
> > Thanks for this! README looks great. Two notes
> > 
> > 1. I think there are a few dependencies that were only used in Document.py and/or Manifest.py, such as `html5_parser` and `lxml`(but possibly more). What do you think about checking and removing such dependencies from setup.py and pyroject.toml?
> > 2. I could be wrong, but it seems like there is still some code for legacy tooling that uses giza/sphinx and deals with building manifests from an html document. I noticed this in `convert_redirects`, for example, but please ignore if you already saw that code and decided to leave it in!
> 
> @anabellabuckvar good catch, I also removed it from those dependencies from `requirement.txt` as well. As for the `convert_redirects.py`, how can I confirm that this was used for legacy tooling?

I'm not sure, it mentions giza-style redirects and versions, but this will likely need further investigation or others on the team might have insight as to whether those code components are still necessary

**Comment by caesarbell** [comment]
> > > Thanks for this! README looks great. Two notes
> > > 
> > > 1. I think there are a few dependencies that were only used in Document.py and/or Manifest.py, such as `html5_parser` and `lxml`(but possibly more). What do you think about checking and removing such dependencies from setup.py and pyroject.toml?
> > > 2. I could be wrong, but it seems like there is still some code for legacy tooling that uses giza/sphinx and deals with building manifests from an html document. I noticed this in `convert_redirects`, for example, but please ignore if you already saw that code and decided to leave it in!
> > 
> > 
> > @anabellabuckvar good catch, I also removed it from those dependencies from `requirement.txt` as well. As for the `convert_redirects.py`, how can I confirm that this was used for legacy tooling?
> 
> I'm not sure, it mentions giza-style redirects and versions, but this will likely need further investigation or others on the team might have insight as to whether those code components are still necessary

@anabellabuckvar, fair, so for learning purposes, `giza/sphinx` technology was only used for legacy tooling? I will raise with the team our question about `convert_redirects` being solely used for legacy tooling.

**Review by anabellabuckvar — COMMENTED** [review]
Looks good! Last thing is make sure to remove the `convert-redirects` script and any references to it

**Comment by anabellabuckvar** [comment]
> > > > Thanks for this! README looks great. Two notes
> > > > 
> > > > 1. I think there are a few dependencies that were only used in Document.py and/or Manifest.py, such as `html5_parser` and `lxml`(but possibly more). What do you think about checking and removing such dependencies from setup.py and pyroject.toml?
> > > > 2. I could be wrong, but it seems like there is still some code for legacy tooling that uses giza/sphinx and deals with building manifests from an html document. I noticed this in `convert_redirects`, for example, but please ignore if you already saw that code and decided to leave it in!
> > > 
> > > 
> > > @anabellabuckvar good catch, I also removed it from those dependencies from `requirement.txt` as well. As for the `convert_redirects.py`, how can I confirm that this was used for legacy tooling?
> > 
> > 
> > I'm not sure, it mentions giza-style redirects and versions, but this will likely need further investigation or others on the team might have insight as to whether those code components are still necessary
> 
> @anabellabuckvar, fair, so for learning purposes, `giza/sphinx` technology was only used for legacy tooling? I will raise with the team our question about `convert_redirects` being solely used for legacy tooling.

AFAIK, yes, those are legacy and we will no longer be supporting that tooling

**Review by anabellabuckvar — APPROVED** [review]
LGTM :)

**Pull request merged**
